import { DevtoolsProvider } from "@providers/devtools";
import { RefineKbarProvider } from "@refinedev/kbar";
import { RefineSnackbarProvider } from "@refinedev/mui";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { ColorModeContextProvider } from "@contexts/color-mode";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ClientProvider } from "../providers/client";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Suspense>
            <RefineKbarProvider>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <RefineSnackbarProvider>
                  <DevtoolsProvider>
                    <ClientProvider>{children}</ClientProvider>
                  </DevtoolsProvider>
                </RefineSnackbarProvider>
              </ColorModeContextProvider>
            </RefineKbarProvider>
          </Suspense>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
